server:
  port: ${PORT:8080}

spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/dental-academy}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc.lob.non_contextual_creation: true
        format_sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  thymeleaf:
    cache: false # enable hot swap for thymeleaf html files

logging:
  level:
    ua.kazo.dentalacademy: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

payment:
  provider: ${PAYMENT_PROVIDER}
  orderPrefix: ${ORDER_PREFIX:}
  paymentTime: 15
  currency: UAH
  callbackHost: ${CALLBACK_HOST}
  liqpay:
    privateKey: ${LIQPAY_PRIVATE_KEY}
    publicKey: ${LIQPAY_PUBLIC_KEY}
  fondy:
    merchantId: ${FONDY_MERCHANT_ID}
    merchantPassword: ${FONDY_MERCHANT_PASSWORD}
  portmone:
    payeeId: ${PORTMONE_PAYEE_ID}
